name: Refresh Leaderboard

on:
  workflow_dispatch:
    schedule:
    - cron: '*/10 12-21 * * *'   # every 5 mins between 8am and 7pm
jobs:
  update-leaderboard:
    runs-on: ubuntu-latest
    env:
      RAPID_GOLF_API_KEY: ${{ secrets.RAPID_GOLF_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.PGA_TRACKER_AUTOMATION}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ env.GITHUB_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Run leaderboard refresh
        run: go run main.go --refresh

      - name: Commit and push changes
        run: |
          git config user.name "mattzech"
          git config user.email "matthewjzech@gmail.com"
          git add docs/index.html
          git add leaderboard.json
          git commit -m "[automation] refresh leaderboard"
          git push
